### ISSUE TITLE
lazy loading?

### ISSUE THREAD

**Issue by rabernat** [euroargodev/argopy#14]
I just tried out the argopy binder and am very impressed! I think this is really fantastic--will be a game changer for the field, making it much easier to access argo data.

My question is about lazy loading. In the binder, one of the first lines is:
```python
ds = argo_loader.region([-85,-45,10.,20.,0,10.]).to_xarray()
```

This takes quite about a minute to run, and it downloads all of the data eagerly. The whole dataset is loaded into memory.

Might it instead be possible to use lazy loading, and have this function return an xarray dataset backed by dask arrays? In this case, the data would be loaded "on demand," i.e. whenever they are actually needed for computation, and could potentially be processed using parallel processing. (You could always recreate the existing behavior by calling `.load()` on the dask data.)

Perhaps this is not really a major issue, since argo data is not that big, but I thought I would raise it for discussion. I imagine it would require some refactoring of the backend data loaders.

**Comment by gmaze** [comment]
Hi @rabernat 
Thanks for having a look to argopy and for raising this point !
You're right: lazy loading would be a very nice way to limit data transfer and to ensure a better user experience.
But when accessing data from an erddap server, I don't really see how to implement this.
And yet, when accessing data from a collection of local netcdf files, this may looks easier.

However, my main concern relates to our initial design: our priority is to to provide data for `standard` users, directly usable for science analysis. We assume `standard` users don't know Argo jargon, dataset specification and simply want a collection of good measurements.
In order to do that, we need to internally process the data. For instance we need to select data according to quality control flags, or according to a specific data management level (like real-time or delayed-mode data). This can get fairly complex and more importantly with regard to laziness, it means that we have to work with 1, 2 or 3 variables to mask fields and provide easy access to one measurement. I imagine that this would give rise to very large complex graphs.

An easy solution is to actually create an `standard` user dataset and to plug argopy to it. This is in active dev elsewhere but not ready for production/diffusion. Check this out for instance:
```python
fs = gcsfs.GCSFileSystem(project='alert-ground-261008', token='anon', access='read_only')
gcsmap = fs.get_mapper('argodata/sdl/GLOBAL_ARGO_SDL2000')
ds = xr.open_zarr(gcsmap)
```

Since we also want to provide data to `expert`, our choice is to access data as close as possible to their original format and then to process them on-demand. As you point out, the Argo dataset is not that big, so this is viable solution for now.

@quai20 is working on Argo index data fetchers (https://github.com/euroargodev/argopy/pull/6), so with regard to performance, we were thinking about this strategy:
- User request data
- Use the Argo index to provide minimal information to user and assess the full request byte size
- Depending on the request characteristics and size, provision the most appropriate backend and dataset to load data from.

**Comment by ocefpaf** [comment]
> But when accessing data from an erddap server, I don't really see how to implement this.
And yet, when accessing data from a collection of local netcdf files, this may looks easier.

You can use the OPeNDAP response of the ERDDAP server but that is a bit awkward. Any other response has the advantage of the server side slice but after that you must download the data.

**Comment by gmaze** [comment]
Yeah @ocefpaf I can't get my head around that.

**Comment by ocefpaf** [comment]
> Yeah @ocefpaf I can't get my head around that.

To be honest I cannot get my head around that as well :-)

ERDDAP is all about server side slicing but after you select your data you cannot load it lazily, you must download it. I believe the sliced dataset is not cached for long, so a new request after a while will generate a new sliced dataset making it hard and/or ineficiente to create workarounds in client libraries like `erddapy`.

That is true for most responses (matlab, csv, netCDF, etc). But the OPeNDAP response **can** do lazy loading. That allows us to create an xarray object, slice locally, and request the rest of the data later when needed, like creating a figure or some sort of operation with the data.

ERDDAP has an OPeNDAP response but that is quite awkward to use b/c all the variables are namespaced (like `s.temp` instead of `temp`), requiring some extra logic to work with. That is a possible alternative for `argopy`. The thing is, there is no advantage of using ERDDAP at all in that case. If there is a nice OPeNDAP server for argo then just use that instead of the ERDDAP OPeNDAP response and you'll have lazy loads "for free."

**Comment by rabernat** [comment]
Even without an opendap endpoint, it is always possible to construct a lazy representation of a remote dataset using dask, delayed functions, etc. Here is an example for the Coperinicus CDS API:
https://github.com/pangeo-data/pangeo-era5/blob/master/lazy_loading_expts.ipynb

Another option is that, if the files are accessible over http or ftp, you can use an fsspec filesystem to read them lazily.
```python
import fsspec
import xarray as xr
with fsspec.open('https://www.ldeo.columbia.edu/~rpa/NOAA_NCDC_ERSST_v3b_SST.nc') as f:
    ds = xr.open_dataset(f, chunks={'time': 1})
```

**Comment by gmaze** [comment]
> to construct a lazy representation of a remote dataset using dask, delayed functions, etc.

With the erddap, there is the possibility to retrieve the equivalent of a ``ncdump -h`` of the request answer:
http://www.ifremer.fr/erddap/tabledap/ArgoFloats.ncHeader?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude%3E=-75&longitude%3C=-65&latitude%3E=10&latitude%3C=20&pres%3E=0&pres%3C=1000.0&time%3E=-2208988800.0&time%3C=4133894400.0&distinct()&orderBy(%22time,pres%22)

will return something like:
```bash
netcdf ArgoFloats_c4e0_cdb0_1388.nc {
  dimensions:
    row = 671925;
    data_mode_strlen = 1;
    position_qc_strlen = 1;
    time_qc_strlen = 1;
    direction_strlen = 1;
    platform_number_strlen = 7;
    pres_qc_strlen = 1;
    temp_qc_strlen = 1;
    psal_qc_strlen = 1;
    pres_adjusted_qc_strlen = 1;
    temp_adjusted_qc_strlen = 1;
    psal_adjusted_qc_strlen = 1;
  variables:
    char data_mode(row=671925, data_mode_strlen=1);
      :_Encoding = "ISO-8859-1";
      :conventions = "R : real time; D : delayed mode; A : real time with adjustment";
      :ioos_category = "Time";
      :long_name = "Delayed mode or real time data";

    double latitude(row=671925);
      :_CoordinateAxisType = "Lat";
      :_FillValue = 99999.0; // double
      :actual_range = 11.224676666666667, 19.999; // double
      :axis = "Y";
      :colorBarMaximum = 90.0; // double
      :colorBarMinimum = -90.0; // double
      :ioos_category = "Location";
      :long_name = "Latitude of the station, best estimate";
      :standard_name = "latitude";
      :units = "degrees_north";
      :valid_max = 90.0; // double
      :valid_min = -90.0; // double
[...]
```
(just the first few lines shown here)

So, would it possible to actually use that to create an "empty"/"lazy" dataset ?

**Comment by ocefpaf** [comment]
> So, would it possible to actually use that to create an "empty"/"lazy" dataset?

Yes but I would avoid that route. You would end up recreating tons of line of code to mock something that we can probably get with other libraries.

@rabernat `fsspec` seems promissing. I never used it before for https. I'll try to implement that in `erddapy` and, if successful, `argopy` will inherit that functionality "for free."

**Comment by ocefpaf** [comment]
@gmaze I'm experimenting with `fsspec` in `erddapy` and this is my first test. Note that I'm not an expert on this but here are my findings so far:

https://nbviewer.jupyter.org/gist/ocefpaf/7444586b3dd926489431627b4a797a99

while the request was faster, and the new `xarray` dataset is "lazy," we cannot really compare cells [2] and [3] b/c the returned xarray dataset objects are different. Also, note that only servers which allow for "range requests" will work properly with `fsspec`, otherwise `fsspec` will have to download the whole data anyways and we won't gain anything, in fact it will be slower.

**Comment by gmaze** [comment]
Thanks @ocefpaf ! 
I'll try to test that in the argopy workflow asap, to check if it benefits time response and memory usage effectively

**Comment by gmaze** [comment]
> @gmaze I'm experimenting with `fsspec` in `erddapy` and this is my first test. Note that I'm not an expert on this but here are my findings so far:
> 
> https://nbviewer.jupyter.org/gist/ocefpaf/7444586b3dd926489431627b4a797a99
> 
> while the request was faster, and the new `xarray` dataset is "lazy," we cannot really compare cells [2] and [3] b/c the returned xarray dataset objects are different. Also, note that only servers which allow for "range requests" will work properly with `fsspec`, otherwise `fsspec` will have to download the whole data anyways and we won't gain anything, in fact it will be slower.

Yes we cannot compare cells [2] and [3] because argopy does a lot of post-processing after the erddapy download, in order to return curated data to standard users. So, we would need to compare eggs with eggs
Note that at this point, we don't use the erddapy to_xarray() method, but rather rely on csv and pandas. We do so because it allows to manage only in memory data, we wanted to avoid temporary files on disk.
I'm going to investigate this solution: to rely on erddapy to_xarray() method to make sure we could be using your fsspec implementation.

I've checked on the last erddapy, it doesn't seem to be using fsspec yet.
(But I've noticed https://github.com/ioos/erddapy/issues/114 that I also encountered and pushed me to get my own erddap url builder).

**Comment by ocefpaf** [comment]
I'm also implementing a netCDF in memory, response. Maybe that will be better than the `csv` one. I'm not sure if xarray support creating a dataset from the in-memory nc object, if so, that can be used in the .to_xarray too. Stay tunned.

**Comment by gmaze** [comment]
Given today's structure of Argo webAPI and argopy choice of client side postprocessing of raw data (standard vs expert), we don't expect a possible lazy loading of Argo data in the near future

Close this issue, to be possibly raised again when data infrastructure will evolve
