### ISSUE TITLE
Move contributing.rst to root directory

### ISSUE THREAD

**Issue by DamienIrving** [euroargodev/argopy#41]
*This comment is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/2425*.

It's common for software repositories to have a `CONTRIBUTING` file in the root directory (along with `LICENSE`, `README`, `CODE_OF_CONDUCT` etc).

You've already got that information in [docs/contributing.rst](https://github.com/euroargodev/argopy/blob/master/docs/contributing.rst), so it might be a good idea to move that file to the root directory. You'll then just need to update [docs/index.rst](https://github.com/euroargodev/argopy/blob/master/docs/index.rst) with something like `.. include:: ../contributing.rst` so that information still appears on your Read the Docs page.

**Comment by gmaze** [comment]
hi @DamienIrving 
I agree that we must have a CONTRIBUTING guideline at the root level on Github. 

But instead of moving the documentation rst file there, I'd rather like to create a CONTRIBUTING.md that explicitly points toward the specific page at https://argopy.readthedocs.io/en/latest/contributing.html 
g
