### ISSUE TITLE
FR? // Filter float/profile data by available measurement (oxygen)?

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [euroargodev/argopy#76]
Aloha ARGOpy team.  First, thanks for these great efforts to make Argo data easier to use and more impactful.  Well done and much appreciated.

This may be a feature request *OR* it may be my ignorance interpreting the docs but I'm unclear if this package provides flags to filter float / profile data to only include floats / profiles with a certain measurement, for example oxygen?

If this isn't possible what approach might one take to try to add this feature?

Thanks again.

**Comment by gmaze** [comment]
Hi @Thomas-Moore-Creative 

Several comments to answer your question:

+ At this point, there is no filter available on the variables fetched. You can still remove non-essential variables after your fetch, using xarray.drop_vars

+ Note that you can select which dataset to fetch, namely:

  - 'phy' for all physical variables, this is the default choice
  - 'bgc' for all biogeochemical variables
  - 'ref' for the physical variables of the core Argo Reference-Dataset used for Quality Control

  [This is documented here.](https://argopy.readthedocs.io/en/latest/data_sources.html#Features)

+ But the 'bgc' dataset is NOT fully implemented nor supported yet (eg #22  )

+ Argo-BGC data support has been delayed because we had to consolidate argopy wrt dependencies for the upcoming release 0.1.7, Argo-BGC support is planned for release 0.1.8

+ Do you think a more finally tuned methodology to filter measurements/variables retrieved would be usefull for BGC data ?

**Comment by Thomas-Moore-Creative** [comment]
@gmaze thank you for the detailed reply. In the short term it looks like #22 holds some useful examples for my use case where I'm just trying to grab oxygen data from the roughly 430 sensors out there in the ocean.

I think that reducing / filtering the data request as finely as possible as early as possible in a workflow use useful but my opinion may be less informed as I'm a very new user (have only read some of the docs and have just installed today)

**Comment by gmaze** [comment]
thanks for your suggestions @Thomas-Moore-Creative !

Closing this issue too much related to #22
