### ISSUE TITLE
Feature Request: Subset index by date?

### ISSUE THREAD

**Issue by cgrdn** [euroargodev/argopy#84]
I'm trying to load profiles from post 2020 for a certain set of floats. It would of course be easy to filter these out using the `to_dataframe()` or `to_xarray()` functions, but I also want to use `idx.plot('trajectory')` for those 2020 and on profiles.  

#### MCVE Code Sample

```python
import datetime as dt
import argopy
argopy.set_options(mode='expert')
fetcher = argopy.IndexFetcher()

my_wmo_list = [
    4902417,
    4902418,
    4902424,
    4902434,
    4902435,
    4902452
]

idx = fetcher.float(my_wmo_list) # want to subset this by date!
# perhaps a kwarg?
# idx = fetcher.float(my_wmo_list, startdate=dt.date(2020, 1, 1))
# could also have an enddate=, but finds all profiles after startdate if not set, as above

```

#### Expected Output

Same indexfetcher object with appropriate dates removed. 

#### Problem Description

Not a problem so much as a desired feature. Of course I can work around this but it would be nice to directly use the plotting features that the indexfetcher object offers!

#### Versions

<details><summary>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252
libhdf5: 1.10.4
libnetcdf: 4.7.3

argopy: 0.1.7
xarray: 0.16.1
pandas: 1.1.1
numpy: 1.19.1
scipy: 1.5.0
fsspec: 0.8.0
erddapy: 0.6.0
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.27.0
distributed: 2.27.0
matplotlib: 3.3.1
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: None
gsw: 3.3.1
setuptools: 49.6.0.post20200814
pip: 20.2.2
conda: 4.9.2
pytest: 6.0.2
IPython: 7.18.1
sphinx: 3.2.1
</summary>
</details>

**Comment by gmaze** [comment]
Hi @cgrdn 
As you mentioned, this could very easily be done afterward on the xarray or dataframe structure with the data
At this point, we prefer not to mix the wmo/cycle approach vs the space/time domain one for clarity, although this could change in the future.
I acknowledge that it leads to more data download than required, but in your use case scenario, it remains a reasonable amount of data.
I close this issue because this feature request could easily be achieved outside of argopy without a significant loss of performances.
Please re-open if you have a use case scenario with performances issue
